name: Build

on: 
  pull_request:
    branches:
    - master
    - dev
  push:
    branches:
    - master
    - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Unity - Build assets
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneWindows64
        unityVersion: 2022.3.5f1
        projectPath: ksp2-papi-assets
        buildMethod: BuildAssets.PerformBuild
    
    - name: Remove build directory
      run: sudo rm -dfr ./build

    - name: Build
      run: |
        dotnet tool restore
        dotnet cake
      #uses: cake-build/cake-action@v1.4.1
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/build/ksp2-papi.zip
