name: Build

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore Cake
      run: dotnet tool restore

    - name: Restore Dependencies
      run: dotnet restore

    - name: Dotnet Build
      run: dotnet cake --target Build -v Diagnostic

    - uses: actions/cache@v4
      with:
        path: ksp2-papi-assets
        key: Library-ksp2papi
        restore-keys: |
          Library-ksp2papi-
          Library-

    - name: Setup Unity - Build assets
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneWindows64
        unityVersion: 2022.3.5f1
        projectPath: ksp2-papi-assets
        buildMethod: BuildAssets.PerformBuild
        buildsPath: ksp2-papi-assets/Build

    - name: Pack Files
      run: dotnet cake --target Pack -e -v Diagnostic

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/build/ksp2-papi.zip
